version: '3'

services:
  app:
    build: .
    command: bash -c 'bundle exec rackup -o 0.0.0.0'
    volumes:
      - .:/app
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - 9292:9292
    stdin_open: true
    tty: true
